# Copyright 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Definition for Docker image that runs the miniuss diagnostic tool.

# To build an image from this Dockerfile:
# docker image build -f Dockerfile_miniuss -t interussplatform/miniuss:tcl4 .

# To run this image:
# docker run \
#     -e MINIUSS_CONTROL_AUTHORIZATION="passphrase for control" \
#     -e MINIUSS_USERNAME="your client ID to retrieve OAuth credentials" \
#     -e MINIUSS_PASSWORD="your client secret to retrieve OAuth credentials" \
#     -p 5000:5000 -d interussplatform/miniuss:tcl4

# For a list of environment variables, see config.py.

FROM python:2

WORKDIR /usr/src/app

RUN pip install --no-cache-dir python-dateutil flask PyJWT djangorestframework cryptography pytz gunicorn shapely requests

COPY . .

ENV MINIUSS_SERVER 0.0.0.0
ENV MINIUSS_PORT 5000

CMD gunicorn miniuss:webapp -b ${MINIUSS_SERVER}:${MINIUSS_PORT} --access-logfile -

EXPOSE $MINIUSS_PORT
