# Copyright 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Definition for Docker image that proxies traffic to the miniuss API service.

# To build an image from this Dockerfile:
# docker image build -f Dockerfile_reverseproxy -t interussplatform/miniuss_reverse_proxy .

# To run this image:
# docker run \
#     -e API_SERVER="storage_api_ip" -e API_PORT="5000" \
#     -p 8121:8121 -d interussplatform/mini_reverse_proxy

# Required environment variables:
#   API_SERVER: Address of the API service.
#   API_PORT: Port on which the API service is listening.

# Optional environment variables:
#   API_PORT_HTTPS: Port on which the InterUSS API will be served via HTTPS (default 8121).
#   SSL_CERT_NAME: File name of SSL certificate (default: cert.pem)
#   SSL_KEY_NAME: File name of SSL private key (default: key.pem)

FROM nginx

COPY nginx_entrypoint.sh .

ENV API_PORT_HTTPS 8121

CMD ./nginx_entrypoint.sh

EXPOSE $INTERUSS_API_PORT_HTTPS
