# Definition for Docker image that runs a simple auth server over HTTP.

# To build an image from this Dockerfile, change to the root folder of this repo then:
# docker image build -f ./authserver/docker/Dockerfile_authserver -t interuss/auth_server ./authserver

# To run this image, change to a working directory containing just public.pem, private.pem, and
# roster.txt (see `auth_server --help` for details) and then execute:
# docker run -v `pwd`:/resources -p 8082:8082 -d interuss/auth_server

# Or, to just run with the demo resources:
# docker run -p 8082:8082 -d interuss/auth_server

# Optional environment variables:
#   INTERUSS_AUTH_SERVER: IP address that will respond to auth server requests (default 0.0.0.0).
#   INTERUSS_AUTH_PORT: Port on which the auth server will be served (default 8082). This port may
#     also be exposed outside the container with -p flag.
#   INTERUSS_VERBOSE: True for more log messages from the auth server (default true).
#   INTERUSS_ISSUER: Text that will appear in 'iss' field of access_tokens (default
#     interuss.org).
#   INTERUSS_AUTH_EXPIRATION: Number of seconds after issuance that access tokens will expire
#     (default 3600).

FROM python:3

WORKDIR /usr/src/app

COPY ./src/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src .

COPY ./docker/private.pem /resources/private.pem
COPY ./docker/public.pem /resources/public.pem
COPY ./docker/roster.txt /resources/roster.txt

ENV INTERUSS_AUTH_SERVER 0.0.0.0
ENV INTERUSS_AUTH_PORT 8082
ENV INTERUSS_AUTH_VERBOSE true
ENV INTERUSS_AUTH_ISSUER interuss.org
ENV INTERUSS_AUTH_EXPIRATION 3600
ENV INTERUSS_AUTH_PUBLIC_KEY /resources/public.pem
ENV INTERUSS_AUTH_PRIVATE_KEY /resources/private.pem
ENV INTERUSS_AUTH_ROSTER /resources/roster.txt

CMD gunicorn auth_server:webapp -b ${INTERUSS_AUTH_SERVER}:${INTERUSS_AUTH_PORT} --access-logfile -

EXPOSE $INTERUSS_AUTH_PORT
